config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :installs
  get 'home/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :events
  resources :profiles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :users

	validates :zip, length: {is: 5}, presence: true

def self.search(search)
 where("city LIKE ?", "%#{search}%")
	end
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user, optional: true
	has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception 
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

def index
	@events = Event.all
	 if params[:search]
	   @events = Event.search(params[:search]).order("created_at DESC")
	 else
	   @events = Event.all.order('created_at DESC')
	 end
end

def show
	@event = Event.find(params[:id])
end

def new
	@event = Event.new
end

def create
	@event = Event.new(event_params)
		if @event.save
			flash[:notice] = "Your event was added."
			redirect_to "/events/"
		else
			flash[:notice] = "Your event was NOT added."
			redirect_to "/events/new"
		end
	end



def edit
	@event = Event.find(params[:id])
end


def update
	@event = Event.find(params[:id])
	@event.address1 = params[:event][:address1]
	@event.address2 = params[:event][:address2]
	@event.city = params[:event][:city]
	@event.state = params[:event][:state]
	@event.zip = params[:event][:zip]
	@event.time_date = params[:event][:time_date]
	@event.title = params[:event][:title]
	@event.description = params[:event][:description]
		if @event.save
			redirect_to event_path
		else
			redirect_to "/events/edit"
		end
end

def destroy
    Event.find(params[:id]).destroy
        redirect_to "/events/"
end

private

    def event_params
      params.require(:event).permit(:address1, :address2, :city, :state, :zip, :time_date, :title, :description)

    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	
def index
	@profiles = Profile.all
end

def show
	@profile = Profile.find(params[:id])
	@events = Event.all
end

def new
	@profile = Profile.new
end

def create
	@profile = Profile.new(profile_params)
	if @profile.save
		flash[:notice] = "Your location has been saved."
		redirect_to profile_path(@profile)
	else
		flash[:notice] = "Your profile was NOT created."
		redirect_to "/events/"
	end
end

def edit
	@profile = Profile.find(params[:id])
end
	

def update
	@profile = Profile.find(params[:id])
	@profile.city = params[:profile][:city]
	puts @profile
	if @profile.save
		redirect_to profile_path
	else
		redirect_to "/profiles/"
	end
end


private
    
    def profile_params
      params.require(:profile).permit(:city)
    
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    end

    def create
        @user = User.where(email: params[:email], password: params[:password]).first
            if @user && @user.password == params[:password]
                session[:user_id] = @user.id
                    redirect_to '/events/new'
            else
                throw "No user"
            end
        end
    def destroy
        session[:user_id] = nil
            redirect_to '/'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<div>

	<%= form_for(@event) do |form| %>  
	<%= form.label :address1 %>:   
	<%= form.text_field :address1 %>  
<p>
	<%= form.label :address2 %>:   
	<%= form.text_field :address2 %> 
	</p>

<p>
	<%= form.label :city %>:   
	<%= form.text_field :city %> 
</p>
<p>
	<%= form.label :state %>:   
	<%= form.text_field :state %> 
</p>
<p>
	<%= form.label :zip %>:   
	<%= form.text_field :zip %> 
</p>
<p>
	<%= form.label :time_date %>:   
	<%= form.text_field :time_date %> 
</p>
<p>
	<%= form.label :title %>:   
	<%= form.text_field :title %> 
</p>
<p>
	<%= form.label :description %>:   
	<%= form.text_field :description %> 
</p>
<p>

</div>

<%= form.submit "Create" %>

<% end %>

<p>
<%= link_to("All Events", "/events/") %>
</p>

app/views/events/index.html.erb
<h1 id ="title-shift"> ALL EVENTS in <span class="last-word"><%=(params[:search])%></span></h1>

<div id="location-container">
  <div id="geolocation"></div>
</div>

	<div id="move">
		<% @events.each do |event| %>
	<div>

<div id = "space">
	<h3><b><%= event.city%>, <%= event.state%> <%=event.zip%></b></h3>
<div id="shift"><h4 id ="title"><%= event.title %></h4>
	<h5><i>Description:</i></h5></h6> <%= event.description%></h6>
	<h5><i>Date of Event:</i></h5> <h6><%= event.time_date %></h6>
</div>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
<h5 id="show"><%= link_to("Show", event_path(event), {:style => 'color:#0052A5'}) %></h5>
<h5 id="cancel"><%= link_to("Cancel Event", event_path(event), method: :delete) %></h5>
<% else %>
<% end %>
</p>
 </div>

<% end %>
</div>

app/views/events/new.html.erb
<h1>Create An Event</h1>

<div id ="new-event">
<p>
	<%= form_for @event do |form| %>
	<%= form.label :address1 %>:
	<%= form.text_field :address1 %>
</p>
<p>
	<%= form.label :address2 %>:
	<%= form.text_field :address2 %>
</p>
<p>
	<%= form.label :city %>:
	<%= form.text_field :city %>
</p>
<p>
	<%= form.label :state %>:
	<%= form.text_field :state %>
</p>
<p>
	<%= form.label :zip %>:
	<%= form.text_field :zip %>
</p>
<p>
	<%= form.label :time_date %>:
	<%= form.text_field :time_date %>
</p>
<p>
	<%= form.label :title %>:
	<%= form.text_field :title %>
</p>
<p>
	<%= form.label :description %>:
	<%= form.text_field :description %>
</p>
<p>

</div>

<%= form.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.description %>

<%= link_to("Add Event", "/events/new") %>

app/views/home/index.html.erb
<div id= "h1-banner">
  <h1 id ="speak-up">Speak <span class="last-word">Up</span></h1>
</div>

<div id= "h2-banner">
  <h2 id ="directions">Enter your city to search upcoming town hall meetings near you:</h2>
</div>

<div id="home-background">
<div id="search">
  <%= form_tag(events_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Events" %>

    <%= submit_tag "SEARCH", id: "button" %>
  <% end %>

  <% if @events.present? %>
    <%= render @events %>
  <% end %>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Speakup</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Arya|Permanent+Marker|Paytone+One|Open+Sans','application.css' %>
  </head>

  <body>


    <ul class="nav">
    </ul>


    <div class="navbar-text-pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <%= link_to "Create an Event", new_event_path %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <script src="//maps.google.com/maps/api/js?key=<%=ENV['GMAPS_API_KEY']%>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

    <script type="text/javascript">

      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: {id: 'geolocation'} }, function(){
        // be aware chrome >= 50 requires https for geolocation to work
        if(navigator.geolocation)
          navigator.geolocation.getCurrentPosition(displayOnMap);
      }
      // function(){
      //     markers = handler.addMarkers([
      //       {
      //         "lat": 41.055887,
      //         "lng": -74.146631,
      //         "picture": {
      //           "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
      //           "width":  32,
      //           "height": 32
      //         },
      //         "infowindow": "hello!"
      //       }
      //     ]);
      //     handler.bounds.extendWith(markers);
      //     handler.fitMapToBounds();
      //   }
      );

      function displayOnMap(position){
        var marker = handler.addMarker({
          lat: position.coords.latitude,
          lng: position.coords.longitude
        });
        handler.map.centerOn(marker);
      };

      function displayOnMap(){
        var markers = handler.addMarkers([
          {
            "lat": 41.055887,
            "lng": -74.146631,
            "infowindow" : "HEALTHCARE REFORM"
          },
          {
            "lat": 40.642409,
            "lng": -74.076036,
            "infowindow" : "Water Bills"
          },
          {
            "lat": 40.621393,
            "lng": -74.006671,
            "infowindow" : "The New America"
          },
          {
            "lat": 40.872534,
            "lng": -73.893391,
            "infowindow" : "I Am A Solution"
          },
          {
            "lat": 40.706092,
            "lng": -73.922471,
            "infowindow" : "She's the Boss: Black Women at Work"
          },
          {
            "lat": 42.061112,
            "lng": -76.818928,
            "infowindow" : "Southport Town Hall Meeting"
          },
          {
            "lat": 42.411745,
            "lng": -77.416597,
            "infowindow" : "Town of Avoca Town Hall Meeting"
          },
          {
            "lat": 41.056094,
            "lng": -73.542164,
            "infowindow" : "Town Hall w/ Sen. Chris Murphy"
          },
          {
            "lat": 43.303043,
            "lng": -73.581468,
            "infowindow" : "American Health Care Act"
          },
          {
            "lat": 42.249239,
            "lng": -73.785824,
            "infowindow" : "Rally to Stop Trumpcare"
          }
        ]);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      }

    </script>
  </body>
</html>

app/views/profiles/edit.html.erb
<h1>Add Your City!</h1>
<div id="sign-up-container">
	<%= form_for(@profile) do |form| %>
	<%= form.label :city %>:
	<%= form.text_field :city %>
<%= form.submit "Update" %>
<% end %>
</div>

app/views/profiles/index.html.erb
<% @profiles.each do |profile| %>


<%= profile.city %><br>

<% end %>

app/views/profiles/new.html.erb
<h1>Add Your City!</h1>

	<%= form_for(@profile) do |form| %>  
	<%= form.label :city %>:   
	<%= form.text_field :city %> 
<%= form.submit "Add" %>
<% end %>

app/views/profiles/show.html.erb
<h1>Events near <%=@profile.city %>!</h1>

<% @events.each do |event| %>

<%= event.description %>

<% end %>

<%= link_to("Add Event", "/events/new") %>